#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path("../lib", __FILE__)
require "generators"

gname = ARGV.shift
order = Integer(ARGV.shift)

gen = Object.const_get("#{gname}Generator").new order

gen.analyze ARGF.read

STDERR.puts gen.stats
Marshal.dump gen, STDOUT
